ekf_odom_node:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.3
    two_d_mode: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    publish_tf: true
    predict_to_current_time: true
    transform_timeout: 0.05
    print_diagnostics: true
    dynamic_process_noise_covariance: false

    # ZED VO: 사용
    odom0: /zed/zed_node/odom
    odom0_config: [true,  true,  false,
                   false, false, true,
                   false, false,  false,
                   false, false, false,
                   false, false, false]
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false
    odom0_pose_rejection_threshold: 4.5
    # odom0_twist_rejection_threshold: 4.5
    # odom0_nodelay: true

    # ZED IMU: yaw rate만 사용(절대 yaw는 GNSS에서)
    imu0: /zed/zed_node/imu/data
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, true,
                  false, false, false]
    imu0_queue_size: 80
    imu0_differential: false
    imu0_relative: false
    # imu0_angular_velocity_rejection_threshold: 3.5
    # imu0_nodelay: true
    imu0_remove_gravitational_acceleration: true

